/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: tech@getlago.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing BillableMetricsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BillableMetricsApiTests
    {
        private BillableMetricsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BillableMetricsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillableMetricsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' BillableMetricsApi
            //Assert.IsInstanceOf(typeof(BillableMetricsApi), instance);
        }

        
        /// <summary>
        /// Test CreateBillableMetric
        /// </summary>
        [Test]
        public void CreateBillableMetricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BillableMetricInput billableMetricInput = null;
            //var response = instance.CreateBillableMetric(billableMetricInput);
            //Assert.IsInstanceOf(typeof(BillableMetric), response, "response is BillableMetric");
        }
        
        /// <summary>
        /// Test DestroyBillableMetric
        /// </summary>
        [Test]
        public void DestroyBillableMetricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //var response = instance.DestroyBillableMetric(code);
            //Assert.IsInstanceOf(typeof(BillableMetric), response, "response is BillableMetric");
        }
        
        /// <summary>
        /// Test FindAllBillableMetricGroups
        /// </summary>
        [Test]
        public void FindAllBillableMetricGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //int? page = null;
            //int? perPage = null;
            //var response = instance.FindAllBillableMetricGroups(code, page, perPage);
            //Assert.IsInstanceOf(typeof(Groups), response, "response is Groups");
        }
        
        /// <summary>
        /// Test FindAllBillableMetrics
        /// </summary>
        [Test]
        public void FindAllBillableMetricsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.FindAllBillableMetrics(page, perPage);
            //Assert.IsInstanceOf(typeof(BillableMetrics), response, "response is BillableMetrics");
        }
        
        /// <summary>
        /// Test FindBillableMetric
        /// </summary>
        [Test]
        public void FindBillableMetricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //var response = instance.FindBillableMetric(code);
            //Assert.IsInstanceOf(typeof(BillableMetric), response, "response is BillableMetric");
        }
        
        /// <summary>
        /// Test UpdateBillableMetric
        /// </summary>
        [Test]
        public void UpdateBillableMetricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //BillableMetricInput billableMetricInput = null;
            //var response = instance.UpdateBillableMetric(code, billableMetricInput);
            //Assert.IsInstanceOf(typeof(BillableMetric), response, "response is BillableMetric");
        }
        
    }

}
