/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetCustomerPortalUrl200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCustomerPortalUrl200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetCustomerPortalUrl200Response
        //private GetCustomerPortalUrl200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCustomerPortalUrl200Response
            //instance = new GetCustomerPortalUrl200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCustomerPortalUrl200Response
        /// </summary>
        [Test]
        public void GetCustomerPortalUrl200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetCustomerPortalUrl200Response
            //Assert.IsInstanceOf(typeof(GetCustomerPortalUrl200Response), instance);
        }


        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }

    }

}
